ST/ST/urls.py
from django.contrib import admin
from django.urls import path, include

from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Sententio/', include('Sententio.urls')),
    url(r'login/$',auth_views.login, name='login'),
    url(r'logout/$', auth_views.logout,{'template_name':'logged_out.html'},name='logout'),
    url('^', include('django.contrib.auth.urls')),
]

ST/Sententio/urls.py
from . import views
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from django.contrib import admin
from django.views.generic.base import RedirectView

app_name = 'Sententio'

urlpatterns = [
    #path(r'tweet_classifier/', views.tweet_classifier, name='tweet_classifier'),
    #path(r'murmuration/',views.murmuration, name='murmuration'),
    url(r'login/$',auth_views.login, {'template_name':'logged_out.html'},name='login'),
    url(r'logout/$', auth_views.logout,{'template_name':'logged_out.html'}, name='logout'),
    url(r'login_redirect/$', views.login_redirect, name='login_redirect'),
    url(r'Classifier_Portal/$',views.Classifier_Portal, name='Classifier_Portal'),
    url(r'Customer_Portal/$',views.Customer_Portal, name='Customer_Portal')
]

ST/Sententio/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
import random
import Sententio
import numpy as np
import json

from django.utils.safestring import SafeData, SafeText, mark_safe

from Sententio.models import Target_Name, Target_Tweet, Tweet, TweetMod, TweetClass, PhraseBit, Reaction, Target_Tweet_Stat

from django.utils.safestring import SafeString

from django.shortcuts import redirect

#Left off here -> need to delete the TweetModeledUnclassed once the TweetModClas is defined
# and then pop up with "no more tweets to classify" <-- this is only if there are none auto-classified (modeled) tweets

from django.template.defaulttags import register

from django.contrib.auth.models import User, Group

@register.filter
def get_all(dictionary, key):
	#splitkey = key.split('.')
	subdict = dictionary.get(key)
	return subdict.get('all')

@register.filter
def get_item(dictionary, key):
	splitkey = key.split('.')
	subdict = dictionary.get(splitkey[0])
	return subdict.get(splitkey[1])

def Classifier_Portal(request):

	print(request)

	try:
		tweetid = request.POST.get("tweetid", "")
		print(request.POST.get("tweetid"))
	except:
		print(request.POST)		

	reactions = Reaction.objects.filter(polarity="POS")
	
	reactset = []
	reactset1 = []
	reactset2 = []

	reactsetflat = []

	for reaction in reactions:
		reactblock = [reaction.name,reaction.opposite.name]
		reactset1.append(reactblock)
	
	reactions = Reaction.objects.filter(polarity="NEU")

	for reaction in reactions:
		reactblock = [reaction.name,reaction.opposite.name]
		reactset2.append(reactblock)

	for reactblock in reactset2:
		if [reactblock[1],reactblock[0]] in reactset2:
			reactset2.remove(reactblock)

	reactset.extend(reactset1)
	reactset.extend(reactset2)

	reactions = Reaction.objects.all()

	for reaction in reactions:
		reactsetflat.append(reaction.name)

	def grab_random():
		global randomtweet
		global index1

		try:
			last = Tweet.objects.filter(classified=False).count() - 1
			index1 = random.randint(0, last)
			#print("index is :" + " " + str(index1))
			randomtweet = Tweet.objects.filter(classified=False)[index1]

		except:
			randomtweet = "empty"

	

	def phrase_classify(tweetclassed,request):


		target_tweet_id = tweetclassed.target_tweet.tweetid
		target_username = tweetclassed.target_tweet.username
		tweet_text = tweetclassed.text

		global rxn_group
		rxn_group = []

		#first, for each sentiment clicked in request, make a TweetClass record

		for key in request.POST:
			value = request.POST[key]
			print(value)
			if value in reactsetflat:
				rxn_group.append(value)

		print("********REACTION GROUP")
		print(rxn_group)

		tmc = TweetClass(tweet=tweetclassed)
		tmc.save()

		tmc = TweetClass.objects.get(tweet=tweetclassed)

		for rxn in rxn_group: #rxn_group will be a block of reactions

			setattr(tmc,rxn,1) #sets the field of the model to 1, signifying
			tmc.save()



		tweet_text = tweet_text.split()
		tweet_len = len(tweet_text)
		x = tweet_len
		phrase_set = []
		tslice_begin = 0 
		tslice_length = 1
		phrase_limit = 3

		while tslice_length <= phrase_limit:
		#while tslice_length <= tweet_len: #have full tweet recorded here
			while (tslice_begin + tslice_length) <= tweet_len:
				phrase = ''
				
				for wordle in tweet_text[tslice_begin:tslice_begin + tslice_length]:
					phrase = phrase + wordle + " "

				phrase = phrase[0:len(phrase)-1]
				#print(phrase)
				print(phrase.encode('ascii', 'ignore'))
				phrase_set.append(phrase)
			
				tslice_begin = tslice_begin + 1

			tslice_begin = 0
			
			tslice_length = tslice_length + 1

		print("")

		phrase_set = list(set(phrase_set))

		for phrase in phrase_set:
			#for rxn in rxn_group:

			try: 
				existing_pb = PhraseBit.objects.get(text=phrase,target_user=target_username,target_tweet=tweetclassed.target_tweet)

				existing_pb.value = existing_pb.value + 1
				existing_pb.save()

				for rxn in rxn_group:
					
					setattr(existing_pb,rxn, getattr(existing_pb,rxn) + 1)
					existing_pb.save()


			except:
				#print("Tweet ALL pb created")

				pb = PhraseBit(text=phrase, target_user=target_username,target_tweet=tweetclassed.target_tweet,value=1) #first pb
				pb.save()

				pb = PhraseBit.objects.get(text=phrase, target_user=target_username,target_tweet=tweetclassed.target_tweet)
				
				for rxn in rxn_group:
					#print("***" + str(rxn))
					setattr(pb,rxn,1) #since its the first one to count toward this phrasebit
					pb.save()


		print("Number of classified phrases = " + str(len(phrase_set)))




	if 'rxn_group' in request.POST:
		print("Successful post!")
		print(request.POST)

		global randomtweet

		#print(tweetid)

		randomtweet = Tweet.objects.get(tweetid=tweetid)

		phrase_classify(randomtweet,request)

		randomtweet.classified = True
		randomtweet.save()
		grab_random()


	else:

		try:
			grab_random()

		except:
			randomtweet = 'empty'


	context = {'randomtweet': randomtweet,'reactions':reactset}

	return render(request, 'Sententio/Classifier_Portal.html', context)


#CLassify incoming tweets using phrase bits

def Customer_Portal(request):
	bar_factor = 0.8
	print(request)
	random_index = 0
	t_tweet_all = Target_Tweet.objects.all()
	random_index = random.randint(0,len(t_tweet_all)-1)
	t_tweet = t_tweet_all[random_index] #test tweet
	t_stats = Target_Tweet_Stat.objects.filter(target_tweet=t_tweet)



	reactions = Reaction.objects.filter(polarity="POS")
	
	reactset = []
	reactset1 = []
	reactset2 = []

	reactsetflat = []

	for reaction in reactions:
		reactblock = [reaction.name,reaction.opposite.name]
		reactset1.append(reactblock)
	
	reactions = Reaction.objects.filter(polarity="NEU")

	for reaction in reactions:
		reactblock = [reaction.name,reaction.opposite.name]
		reactset2.append(reactblock)

	for reactblock in reactset2:
		if [reactblock[1],reactblock[0]] in reactset2:
			reactset2.remove(reactblock)

	reactset.extend(reactset1)
	reactset.extend(reactset2)

	reactions = Reaction.objects.all()

	for reaction in reactions:
		reactsetflat.append(reaction.name)

	hello_world = "HELLOOOO WORLD."

	t_stat_set = {}

	for react in reactsetflat:
		for t_stat in t_stats:
			#print(str(t_stat.reaction.name) + " | " + str(react))
			if t_stat.reaction.name == react:
				t_stat_set[react] = {'all': round(t_stat.avg_allval_mod,1), 'user': round(t_stat.avg_userval_mod,1),'tweet': round(t_stat.avg_tweetval_mod,1)} #this adds the three levels for that reactions
			
			else:
				print("No match for " + react)
				

	reactset1_rev = []
	reactset2_rev = []

	for item in reactset1:
		reactblock = [item[1],item[0]]
		reactset1_rev.append(reactblock)

	for item in reactset2:
		reactblock = [item[1],item[0]]
		reactset2_rev.append(reactblock)

	reactpairs1 = []
	reactpairs2 = []

	for reactpair in reactset1_rev:
		reactpair_val = [0,0]
		for t_stat in t_stats:
			if t_stat.reaction.name == reactpair[0]:
				reactpair_val[0] = t_stat.avg_allval_mod

			if t_stat.reaction.name == reactpair[1]:
				reactpair_val[1] = t_stat.avg_allval_mod

		reactpairs1.append(reactpair_val)

	for reactpair in reactset2_rev:
		reactpair_val = [0,0]
		for t_stat in t_stats:
			if t_stat.reaction.name == reactpair[0]:
				reactpair_val[0] = t_stat.avg_allval_mod

			if t_stat.reaction.name == reactpair[1]:
				reactpair_val[1] = t_stat.avg_allval_mod

		reactpairs2.append(reactpair_val)

	reactpairs_diff1 = []
	reactpairs_diff2 = []

	for item in reactpairs1:
		reactpairs_diff1.append(abs(item[1]+item[0]))

	for item in reactpairs2:
		reactpairs_diff2.append(abs(item[1]+item[0]))

	print(t_stat_set)

	reactpairs_and_diff1 = []
	reactpairs_and_diff2 = []

	n = 0

	for item in reactset1_rev:
		block = [item,reactpairs_diff1[n]]
		reactpairs_and_diff1.append(block)
		n = n+1

	n = 0

	for item in reactset2_rev:
		block = [item,reactpairs_diff2[n]]
		reactpairs_and_diff2.append(block)
		n = n+1

	rpad_temp1 = []
	rpad_temp2 = []
	#rpad_temp.append(reactpairs_and_diff[0])

	n = 1

	while n < len(reactpairs_and_diff1):
		rpad_temp1.append(reactpairs_and_diff1[n])
		n = n+1

	n = 0

	while n < len(reactpairs_and_diff2):
		rpad_temp2.append(reactpairs_and_diff2[n])
		n = n+1

	rpad_temp1.sort(key=lambda x: x[1], reverse=True)
	rpad_temp2.sort(key=lambda x: x[1], reverse=False)
	#unsorted_list.sort(key=lambda x: x[3])

	rpad_ord1 = []
	rpad_ord2 = []

	rpad_ord1.append(reactpairs_and_diff1[0])

	for item in rpad_temp1:
		rpad_ord1.append(item)

	for item in rpad_temp2:
		rpad_ord2.append(item)

	reactset1 = [] #clear the original react set
	reactset2 = []

	for item in rpad_ord1:
		reactset1.append(item[0])

	for item in rpad_ord2:
		reactset2.append(item[0])


	context = {'t_tweet':t_tweet,'t_stat_set':t_stat_set,'reactset':reactset,'reactset1':reactset1,'reactset2':reactset2,'bar_factor':bar_factor}

	return render(request, 'Sententio/Customer_Portal.html', context)

def TweetModeler(tweet): #takes an incoming tweet 
	
	#tweets = Tweet.objects.filter(modeled=False)

	rxn_group = []

	rxns = Reaction.objects.all()

	check_block = []

	for rxn in rxns:
		rxn_group.append(rxn.name)

	target_tweet_id = tweet.target_tweet.tweetid
	target_username = tweet.target_tweet.username
	tweet_text = tweet.text

	tweet_text = tweet_text.split()
	tweet_len = len(tweet_text)
	x = tweet_len
	phrase_set = []
	tslice_begin = 0 
	tslice_length = 1
	phrase_limit = 3

	while tslice_length <= phrase_limit:
	#while tslice_length <= tweet_len: #have full tweet recorded here
		while (tslice_begin + tslice_length) <= tweet_len:
			phrase = ''
			
			for wordle in tweet_text[tslice_begin:tslice_begin + tslice_length]:
				phrase = phrase + wordle + " "

			phrase = phrase[0:len(phrase)-1]
			#print(phrase)
			#print(phrase.encode('ascii', 'ignore'))
			phrase_set.append(phrase)
		
			tslice_begin = tslice_begin + 1

		tslice_begin = 0
		
		tslice_length = tslice_length + 1

	print("")

	phrase_set = list(set(phrase_set))

	phrase_value_block = []

	phrase_set_length = len(phrase_set)

ST/Sententio/templates/Sententio/Classifier_Portal.html
<body>

<title>Classifier Portal</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Sententio/style.css' %}" />



<div class='main_area'>

	<div class='title_area'>

		<h1>Classifier Portal</h1>

	</div>

	<div class='content_area_1'>

		{% if randomtweet == "empty" %}
			<h1>No more tweets to classify</h1>
		{% else %}
			<h2>{{randomtweet.target_tweet}}</h2>
			<h1 id ={{randomtweet.tweetid}} >{{randomtweet.text}}</h1>
		{% endif %}

		{% if randomtweet == "empty" %}

		{% else %}
			<div class="choice_row">
				<form action="{% url 'Sententio:Classifier_Portal' %}" method="post">
					
					{% csrf_token %}

					{% for reaction in reactions %}

					<div class="choice_option">
					<input type="checkbox" id="{{reaction.0}}{{ forloop.counter }}" value="{{reaction.0}}" name="{{reaction.0}}"/>
					<label for="{{reaction.0}}{{ forloop.counter }}">{{reaction.0}}</label><br />
					</div>

					<div class="choice_option">
					<input type="checkbox" id="{{reaction.1}}{{ forloop.counter }}" value="{{reaction.1}}" name="{{reaction.1}}"/>
					<label for="{{reaction.1}}{{ forloop.counter }}">{{reaction.1}}</label><br />
					</div>

					<br>
					
					{% endfor %}
					<br>
					<input type="hidden" name='tweetid' value="{{randomtweet.tweetid}}"/>
					<input type="hidden" name='rxn_group' value='rxn_group'/>
					<input type="submit" value="Classify" />

				</form>
			</div>
		{% endif %}

	</div>

</div>



</body>

ST/Sententio/templates/Sententio/Customer_Portal.html
<body>

<title>Murmuration</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

{% load static %}
{% load mathfilters %}

<link rel="stylesheet" type="text/css" href="{% static 'Sententio/style.css' %}" />

<div class='main_area'>

	<div class='title_area'>

		<h1>{{t_tweet.username}}</h1>
		<h2 style="margin-bottom: 50px;">{{t_tweet.text}}</h2>

	</div>

	<div class='content_area_1'>
		<div class='graph_box'>

		<!-- 	<div>{{t_stat_set}}
			</div> -->

			<div class='table'>
				{% for reactpair in reactset1 %}
					<div class='table_row'>
						<div class='table_cell' style="width: 10%; text-align: right;"><div class="react_text">{{reactpair.0}}</div></div>
						
						<div class='table_cell' style="width: 40%; border-right: solid 3px black;">
							<div style="display: table; width: 100%;">
							{% for t_stat in t_stat_set %}
								{% if t_stat == reactpair.0 %}
									{% with t_stat|add:".tweet" as phrase %}
									<div class='table_row'>
										<div title='Tweet Level' class="bar_left_tweet" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: right; margin-right: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}

									{% with t_stat|add:".user" as phrase %}
									<div class='table_row'>
										<div title='User Level' class="bar_left_user" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: right; margin-right: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}

									{% with t_stat|add:".all" as phrase %}
									<div class='table_row'>
										<div title='All Level' class="bar_left_all" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: right; margin-right: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}
								{% endif %}
							{% endfor %}
						</div>
						</div>

						<div class='table_cell' style="width: 40%; border-left: solid 3px black;">
							<div style="display: table; width: 100%;">
							{% for t_stat in t_stat_set %}
								{% if t_stat == reactpair.1 %}
									{% with t_stat|add:".tweet" as phrase %}
									<div class='table_row'>
										<div title='Tweet Level' class="bar_right_tweet" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: left; margin-left: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}

									{% with t_stat|add:".user" as phrase %}
									<div class='table_row'>
										<div title='User Level' class="bar_right_user" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: left; margin-left: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}

									{% with t_stat|add:".all" as phrase %}
									<div class='table_row'>
										<div title='All Level' class="bar_right_all" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: left; margin-left: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}
								{% endif %}
							{% endfor %}
						</div>
						</div>
						
						<div class='table_cell' style="width: 10%; text-align: left;"><div class="react_text">{{reactpair.1}}</div></div>
					</div>

				{% endfor %}

				{% for reactpair in reactset2 %}
					<div class='table_row'>
						<div class='table_cell' style="width: 10%; text-align: right;"><div class="react_text">{{reactpair.0}}</div></div>
						
						<div class='table_cell' style="width: 40%; border-right: solid 3px black;">
							<div style="display: table; width: 100%;">
							{% for t_stat in t_stat_set %}
								{% if t_stat == reactpair.0 %}
									{% with t_stat|add:".tweet" as phrase %}
									<div class='table_row'>
										<div title='Tweet Level' class="bar_left_tweet2" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: right; margin-right: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}

									{% with t_stat|add:".user" as phrase %}
									<div class='table_row'>
										<div title='User Level' class="bar_left_user2" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: right; margin-right: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}

									{% with t_stat|add:".all" as phrase %}
									<div class='table_row'>
										<div title='All Level' class="bar_left_all2" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: right; margin-right: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}
								{% endif %}
							{% endfor %}
						</div>
						</div>

						<div class='table_cell' style="width: 40%; border-left: solid 3px black;">
							<div style="display: table; width: 100%;">
							{% for t_stat in t_stat_set %}
								{% if t_stat == reactpair.1 %}
									{% with t_stat|add:".tweet" as phrase %}
									<div class='table_row'>
										<div title='Tweet Level' class="bar_right_tweet2" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: left; margin-left: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}

									{% with t_stat|add:".user" as phrase %}
									<div class='table_row'>
										<div title='User Level' class="bar_right_user2" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: left; margin-left: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}

									{% with t_stat|add:".all" as phrase %}
									<div class='table_row'>
										<div title='All Level' class="bar_right_all2" style="width:{% with answer=t_stat_set|get_item:phrase %}{{ answer|mul:bar_factor }}{% endwith %}%;"></div><div style="display:inline-block; float: left; margin-left: 3px;">{{ t_stat_set|get_item:phrase }}%</div>
									</div>
									{% endwith %}
								{% endif %}
							{% endfor %}
						</div>
						</div>
						
						<div class='table_cell' style="width: 10%; text-align: left;"><div class="react_text">{{reactpair.1}}</div></div>
					</div>

				{% endfor %}
			</div>



		</div>
	</div>
</div>



</body>

ST/Sententio/templates/Sententio/tweet_classifier.html
<body>

<title>Tweet Classifier</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="{% static 'Sententio/style.css' %}" />

{% load static %}

<div class='main_area'>

	<div class='title_area'>

		<h1>Classifier Portal</h1>

	</div>

	<div class='content_area_1'>

		{% if randomtweet == "empty" %}
			<h1>No more tweets to classify</h1>
		{% else %}
			<h2>{{randomtweet.target_tweet}}</h2>
			<h1 id ={{randomtweet.tweetid}} >{{randomtweet.text}}</h1>
		{% endif %}

		{% if randomtweet == "empty" %}

		{% else %}
			<div class="choice_row">
				<form action="{% url 'Sententio:tweet_classifier' %}" method="post">
					
					{% csrf_token %}

					{% for reaction in reactions %}

					<div class="choice_option">
					<input type="checkbox" id="{{reaction.0}}{{ forloop.counter }}" value="{{reaction.0}}" name="{{reaction.0}}"/>
					<label for="{{reaction.0}}{{ forloop.counter }}">{{reaction.0}}</label><br />
					</div>

					<div class="choice_option">
					<input type="checkbox" id="{{reaction.1}}{{ forloop.counter }}" value="{{reaction.1}}" name="{{reaction.1}}"/>
					<label for="{{reaction.1}}{{ forloop.counter }}">{{reaction.1}}</label><br />
					</div>

					<br>
					
					{% endfor %}
					<br>
					<input type="hidden" name='tweetid' value="{{randomtweet.tweetid}}"/>
					<input type="hidden" name='rxn_group' value='rxn_group'/>
					<input type="submit" value="Classify" />

				</form>
			</div>
		{% endif %}
		
	</div>

</div>



</body>